### PR TITLE
CAKE-5389 | Enable hulu campaign on specific communities

### PR DESCRIPTION
**Pull request by JoshuaRogan**
## Links

* http://wikia-inc.atlassian.net/browse/CAKE-5389

## Description

* Show a big unit and small unit on article page when it's in the hulu wiki set
* Show a big unit on the search page when it's in the hulu wiki set
* Style units

## Reviewers

@Wikia/cake

### CODE REVIEW

**Review by vforge — COMMENTED** [review]
LGTM

**Comment by mklucsarits** [comment]
Looking good

**Review by vforge — APPROVED** [review]

**Comment by JoshuaRogan** [comment]
The way the code is now it looks like there is no need for the big unit in the JSON file. It's always using the non big one

**Comment by cschucode** [comment]
CAKE-5346 is asking for 3-item and Search units as well. This is going to require a small unit for subheading text as well as a change in the `_getHuluUnit` logic.

Unless, we want it to say `Recommended For You` on all Hulu units no matter where they are.

**Pull request merged**
