### PR TITLE
XW-3939 | Single file that can work for server and fastboot-server fo…

### PR DESCRIPTION
**Pull request by hakubo**
@Wikia/x-wing @rogatty 

I need to rename server folder
otherwise ember serve fails

but to do that I need to update path in chef-repo
https://github.com/Wikia/chef-repo/blob/master/cookbooks/mobile-wiki/templates/default/sv-mobile-wiki-run.erb#L33

### CODE REVIEW

**Review by rogatty — APPROVED** [review]

**Comment by rogatty** [comment]
@kvas-damian do you remember the reason why we used `server/app/server.js` and not `server.js` as we wanted initially? There was _some_ reason...

**Comment by hakubo** [comment]
I think server.js would not work as well
as 
ember serve
would like to import it
and it would die

**Comment by rogatty** [comment]
I don't think it was that. I'd try `fastboot-server.js` before `server/app/server.js` ;) I believe there was some other reason but can't remember it.

**Comment by rogatty** [comment]
Anyway @hakubo, I wouldn't worry too much about it. The current change shouldn't break anything, and in the future you'll test what happens when you change the path in chef.

**Comment by kvas-damian** [comment]
@rogatty AFAIR it was related to backwards compatibility. We were introducing a lot of changes in FastBoot project and we wanted to avoid this one (code on old branches won't work now). Also we were running fastboot and non-fastboot version in parallel, so we needed server runner to work the same on both platforms.

**Comment by rogatty** [comment]
>we were running fastboot and non-fastboot version in parallel

Oh, I think it was that, thanks!

**Pull request merged**
