### PR TITLE
ADEN-7187 Update mercury-shared version

### PR DESCRIPTION
**Pull request by dmnsobczak**

### CODE REVIEW

**Comment by rogatty** [comment]
Quoting @hakubo:
>when working on mobile-wiki please use npm >6.0.1
>shape of package-lock.json changed a bit

I think that's why there are 1329 lines changes.

**Comment by dmnsobczak** [comment]
@rogatty 
```
npm --version
6.1.0
```

**Comment by rogatty** [comment]
Huh :thinking: 
Looks like npm used `http://artifactory.wikia-inc.com/artifactory/api/npm/npm-source` for all dependencies while https://github.com/Wikia/mobile-wiki/blob/dev/.npmrc#L4 tells it not to. @hakubo any ideas why it happens? I don't think it's a blocker, though.

**Review by rogatty — APPROVED** [review]

**Comment by hakubo** [comment]
Npm cache clean - - force could help
Then rm lock file
And npm install again

**Pull request merged**
